# .github/workflows/build-windows-exe.yml

name: Build Windows Executable # 工作流名称

on:
  push:
    branches: [ main ] # 当代码推送到 main 分支时触发
  workflow_dispatch: # 允许手动触发

jobs:
  build:
    runs-on: windows-latest # 指定在最新的 Windows 服务器上运行

    steps:
    - name: Checkout repository # 第一步：拉取你的代码
      uses: actions/checkout@v3

    - name: Set up Python # 第二步：安装 Python 环境
      uses: actions/setup-python@v4
      with:
        python-version: '3.12' # 可以指定你需要的 Python 版本

    - name: Install dependencies # 第三步：安装所有依赖库
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build with PyInstaller # 第四步：运行 PyInstaller 打包
      run: |
        pyinstaller --noconfirm --onefile --windowed devices_inspection.py # 将 your_script_name.py 替换为你的主文件名

    - name: Upload artifact # 第五步：上传打包好的 .exe 文件
      uses: actions/upload-artifact@v3
      with:
        name: Windows-EXE # 上传文件的名称
        path: dist/ # PyInstaller 生成的 dist 文件夹
