# .github/workflows/build-windows-exe.yml

name: Build Windows Executable # 工作流名称

on:
  push:
    branches: [ "main", "master" ] # 当代码推送到 main 或 master 分支时触发
  workflow_dispatch: # 允许手动触发

jobs:
  build:
    runs-on: windows-latest # 指定在最新的 Windows 服务器上运行

    steps:
    # 第一步：拉取你的代码
    # 更新：从 v3 更新到 v4
    - name: Checkout repository
      uses: actions/checkout@v4

    # 第二步：安装 Python 环境
    # 更新：从 v4 更新到 v5
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10' # 可以指定你需要的 Python 版本

    # 第三步：安装所有依赖库
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # 第四步：运行 PyInstaller 打包
    # 注意：请务必将 'your_script_name.py' 替换为你的主文件名
    # --windowed 用于GUI程序，如果你的程序是命令行工具，请使用 --console 或者直接去掉这个参数
    - name: Build with PyInstaller
      run: pyinstaller --noconfirm --onefile --console devices_inspection.py

    # 第五步：上传打包好的 .exe 文件
    # 关键更新：从 v3 更新到 v4
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Windows-EXE # 上传文件的名称
        path: dist/ # PyInstaller 生成的 dist 文件夹
